services:
  - type: web
    name: mboka-care-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
