# Generated by Django 4.2.7 on 2026-02-17 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('MEDICATION', 'Médicament'), ('APPOINTMENT', 'Rendez-vous'), ('EXAM', 'Examen médical'), ('VACCINATION', 'Vaccination'), ('OTHER', 'Autre')], default='MEDICATION', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('medication_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('CUSTOM', 'Personnalisé'), ('ONE_TIME', 'Une fois')], default='DAILY', max_length=20)),
                ('time_slots', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('local_only', models.BooleanField(default=False)),
                ('notify_patient', models.BooleanField(default=True)),
                ('notify_followers', models.BooleanField(default=False)),
                ('notify_doctor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.familymember')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Rappel',
                'verbose_name_plural': 'Rappels',
                'db_table': 'reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('scheduled_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('TAKEN', 'Pris'), ('MISSED', 'Manqué'), ('DELAYED', 'Retardé'), ('SKIPPED', 'Sauté volontairement')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('notification_sent_to_patient', models.BooleanField(default=False)),
                ('notification_sent_to_followers', models.BooleanField(default=False)),
                ('notification_sent_to_doctor', models.BooleanField(default=False)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reminders.reminder')),
            ],
            options={
                'verbose_name': 'Log de Rappel',
                'verbose_name_plural': 'Logs de Rappels',
                'db_table': 'reminder_logs',
                'ordering': ['-scheduled_datetime'],
                'indexes': [models.Index(fields=['reminder', 'scheduled_date'], name='reminder_lo_reminde_08957c_idx'), models.Index(fields=['status'], name='reminder_lo_status_d724c7_idx')],
            },
        ),
    ]
