# Generated by Django 4.2.7 on 2026-02-17 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie Santé',
                'verbose_name_plural': 'Catégories Santé',
                'db_table': 'health_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('VIDEO', 'Vidéo'), ('ARTICLE', 'Article'), ('INFOGRAPHIC', 'Infographie'), ('GUIDE', 'Guide')], default='VIDEO', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('article_content', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='health_priority/thumbnails/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='health_priority/covers/')),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_title', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('warnings', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='health_priority.healthcategory')),
            ],
            options={
                'verbose_name': 'Contenu Santé',
                'verbose_name_plural': 'Contenus Santé',
                'db_table': 'health_contents',
                'ordering': ['-is_featured', 'order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='UserContentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_watched_position', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='health_priority.healthcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Utilisateur',
                'verbose_name_plural': 'Progressions Utilisateurs',
                'db_table': 'user_content_progress',
                'indexes': [models.Index(fields=['user', 'completed'], name='user_conten_user_id_afb695_idx')],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='SavedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='health_priority.healthcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_health_contents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contenu Enregistré',
                'verbose_name_plural': 'Contenus Enregistrés',
                'db_table': 'saved_health_contents',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.AddIndex(
            model_name='healthcontent',
            index=models.Index(fields=['category', 'is_active'], name='health_cont_categor_fb66f9_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcontent',
            index=models.Index(fields=['content_type'], name='health_cont_content_1a9fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='healthcontent',
            index=models.Index(fields=['slug'], name='health_cont_slug_3eb493_idx'),
        ),
    ]
