# Generated by Django 4.2.7 on 2026-02-17 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('LEVEL_1', 'Public (QR Code)'), ('LEVEL_2', 'Médecin autorisé'), ('LEVEL_3', 'Historique complet')], default='LEVEL_3', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('record_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.familymember')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Dossier Médical',
                'verbose_name_plural': 'Dossiers Médicaux',
                'db_table': 'medical_records',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ANALYSIS', 'Analyse médicale'), ('PRESCRIPTION', 'Ordonnance'), ('XRAY', 'Radiographie'), ('SCAN', 'Scanner'), ('MRI', 'IRM'), ('REPORT', 'Compte-rendu'), ('VACCINATION', 'Carnet de vaccination'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_date', models.DateField()),
                ('access_level', models.CharField(choices=[('LEVEL_1', 'Public (QR Code)'), ('LEVEL_2', 'Médecin autorisé'), ('LEVEL_3', 'Historique complet')], default='LEVEL_3', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.familymember')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Médical',
                'verbose_name_plural': 'Documents Médicaux',
                'db_table': 'medical_documents',
                'ordering': ['-document_date'],
            },
        ),
    ]
