# Generated by Django 4.2.7 on 2026-02-17 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSync',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminders_last_sync', models.DateTimeField(blank=True, null=True)),
                ('documents_last_sync', models.DateTimeField(blank=True, null=True)),
                ('medical_records_last_sync', models.DateTimeField(blank=True, null=True)),
                ('consents_last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_full_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_sync', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dernière Synchronisation',
                'verbose_name_plural': 'Dernières Synchronisations',
                'db_table': 'last_sync',
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Mise à jour'), ('DELETE', 'Suppression')], max_length=10)),
                ('data', models.JSONField()),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File de Synchronisation',
                'verbose_name_plural': 'Files de Synchronisation',
                'db_table': 'sync_queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'synced'], name='sync_queue_user_id_ac3ac3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='sync_queue_entity__044a1c_idx'), models.Index(fields=['created_at'], name='sync_queue_created_0b1bd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('items_uploaded', models.IntegerField(default=0)),
                ('items_downloaded', models.IntegerField(default=0)),
                ('conflicts_detected', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Réussi'), ('PARTIAL', 'Partiel'), ('FAILED', 'Échoué')], default='SUCCESS', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Synchronisation',
                'verbose_name_plural': 'Logs de Synchronisation',
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='sync_logs_user_id_286bdc_idx'), models.Index(fields=['status'], name='sync_logs_status_e8f5ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('client_version', models.JSONField()),
                ('server_version', models.JSONField()),
                ('client_updated_at', models.DateTimeField()),
                ('server_updated_at', models.DateTimeField()),
                ('resolution', models.CharField(choices=[('PENDING', 'En attente'), ('USE_SERVER', 'Version serveur'), ('USE_CLIENT', 'Version client'), ('MERGED', 'Fusionné'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('resolved_version', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conflit de Synchronisation',
                'verbose_name_plural': 'Conflits de Synchronisation',
                'db_table': 'sync_conflicts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'resolution'], name='sync_confli_user_id_233659_idx'), models.Index(fields=['entity_type', 'entity_id'], name='sync_confli_entity__f899f6_idx')],
            },
        ),
    ]
