# Generated by Django 4.2.7 on 2026-02-16 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('country_residence', models.CharField(max_length=100)),
                ('city_residence', models.CharField(max_length=100)),
                ('district_residence', models.CharField(max_length=100)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_notes', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('account_type', models.CharField(choices=[('INDIVIDUAL', 'Individuel'), ('FAMILY_CHIEF', 'Chef de famille')], default='INDIVIDUAL', max_length=20)),
                ('qr_public_payload', models.JSONField(blank=True, default=dict)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Patient',
                'verbose_name_plural': 'Profils Patients',
                'db_table': 'patient_profiles',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.CharField(max_length=100)),
                ('country_residence', models.CharField(max_length=100)),
                ('city_residence', models.CharField(max_length=100)),
                ('district_residence', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('CHILD', 'Enfant'), ('SPOUSE', 'Conjoint(e)'), ('PARENT', 'Parent'), ('SIBLING', 'Frère/Sœur'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('chronic_conditions', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('emergency_notes', models.TextField(blank=True)),
                ('qr_public_payload', models.JSONField(blank=True, default=dict)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/family/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Membre de Famille',
                'verbose_name_plural': 'Membres de Famille',
                'db_table': 'family_members',
            },
        ),
        migrations.AddIndex(
            model_name='patientprofile',
            index=models.Index(fields=['account_type'], name='patient_pro_account_9925c6_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family_chief', 'is_active'], name='family_memb_family__c76976_idx'),
        ),
    ]
