# Generated by Django 4.2.7 on 2026-02-17 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=200)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('hospital_affiliation', models.CharField(blank=True, max_length=200)),
                ('practice_country', models.CharField(max_length=100)),
                ('practice_city', models.CharField(max_length=100)),
                ('practice_district', models.CharField(max_length=100)),
                ('practice_address', models.TextField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='doctor_verification/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Médecin',
                'verbose_name_plural': 'Profils Médecins',
                'db_table': 'doctor_profiles',
            },
        ),
    ]
