# Generated by Django 4.2.7 on 2026-02-17 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('FAMILY', 'Famille'), ('CAREGIVER', 'Garde-malade'), ('FRIEND', 'Ami proche'), ('OTHER', 'Autre')], default='FAMILY', max_length=20)),
                ('receive_medication_alerts', models.BooleanField(default=True)),
                ('receive_appointment_reminders', models.BooleanField(default=True)),
                ('receive_emergency_alerts', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Proche Suiveur',
                'verbose_name_plural': 'Proches Suiveurs',
                'db_table': 'patient_followers',
                'indexes': [models.Index(fields=['patient', 'active'], name='patient_fol_patient_086ded_idx'), models.Index(fields=['follower', 'active'], name='patient_fol_followe_4ead62_idx')],
                'unique_together': {('patient', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='EmergencyAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('helper_name', models.CharField(blank=True, max_length=200)),
                ('helper_phone', models.CharField(blank=True, max_length=20)),
                ('qr_code_scanned', models.CharField(max_length=500)),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('access_location', models.JSONField(blank=True, null=True)),
                ('offline_mode', models.BooleanField(default=False)),
                ('synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to='patients.familymember')),
                ('helper_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_helps_provided', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_accesses', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': "Accès d'Urgence",
                'verbose_name_plural': "Accès d'Urgence",
                'db_table': 'emergency_accesses',
                'ordering': ['-access_timestamp'],
                'indexes': [models.Index(fields=['access_timestamp'], name='emergency_a_access__e247e3_idx'), models.Index(fields=['synced'], name='emergency_a_synced_853694_idx')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('LEVEL_1', 'Public (QR Code)'), ('LEVEL_2', 'Médecin autorisé'), ('LEVEL_3', 'Historique complet')], default='LEVEL_2', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consent_type', models.CharField(choices=[('EXPLICIT', 'Consentement explicite'), ('EMERGENCY', 'Urgence médicale'), ('TEMPORARY', 'Temporaire')], default='EXPLICIT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_given', to='patients.patientprofile')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consents_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consentement',
                'verbose_name_plural': 'Consentements',
                'db_table': 'consents',
                'indexes': [models.Index(fields=['patient', 'active'], name='consents_patient_5c752f_idx'), models.Index(fields=['granted_to', 'active'], name='consents_granted_30da6d_idx')],
                'unique_together': {('patient', 'granted_to', 'active')},
            },
        ),
    ]
